# Generated by Django 5.0.1 on 2024-02-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deTextByEar', '0002_detextbyear_translation_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('audios', models.ManyToManyField(to='deTextByEar.detextbyear')),
            ],
        ),
    ]
