# Generated by Django 5.0.1 on 2024-02-11 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deTextByEar', '0003_playlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detextbyear',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='detextbyear',
            name='translation_keywords',
        ),
    ]
