# Generated by Django 5.0.1 on 2024-02-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_word', models.CharField(default='none', max_length=255)),
                ('translated_word', models.CharField(default='none', max_length=255)),
                ('auxiliary_words', models.JSONField(default=dict)),
                ('word_level', models.CharField(default='none', max_length=2)),
            ],
        ),
    ]
