# Generated by Django 5.0.1 on 2024-02-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerbWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('translation', models.CharField(max_length=100)),
                ('verb', models.CharField(max_length=100)),
                ('prefix', models.CharField(max_length=100)),
            ],
        ),
    ]
