# Generated by Django 5.0.1 on 2024-02-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deVerbs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verbword',
            name='prefix',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='verbword',
            name='verb',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
